### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by QuLogic** [jupyter/jupyter-sphinx-theme#15]
There is no LICENSE, LICENSE.md, LICENSE.rst, or LICENSE.txt. There is a `BOOTSTRAP_THEME_LICENSE.txt`, but it's not really clear to what this applies, since the name implies that it's only some smaller part of the repo.

`setup.py` states MIT, so it would be good to include a license file that says so.

**Comment by rgbkrk** [comment]
The license should be BSD-3 here in Jupyter, I've submitted #16 for this. Thanks for raising it up.
