### ISSUE TITLE
Missing jupyter.css

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter-sphinx-theme#5]
I might just be missing an installation step for css. Here's the traceback:

<img width="1243" alt="screen shot 2016-03-23 at 9 40 57 pm" src="https://cloud.githubusercontent.com/assets/2680980/14008608/19e3f6de-f140-11e5-9d00-ee67e70e9ed5.png">

**Comment by willingc** [comment]
The docs did build without the css so that is a plus.

**Comment by jdfreder** [comment]
I've been blindly working on this, I've yet to build/test locally.  I assumed relative paths worked in jinja includes, but it looks like it searches in the template directly regardless.

Side note, what's the color scheme you use in your terminal?  I really like it!

**Comment by willingc** [comment]
I think it is not finding jupyter.css. I've been playing around on this branch in my repo: https://github.com/willingc/jupyterhub/tree/try-theme

For the terminal, Monokai Soda is my flavor of the month (https://github.com/mbadolato/iTerm2-Color-Schemes#monokai-soda). I like Flatland as well. Though truth be told every month or so I switch it up.

**Comment by jdfreder** [comment]
This should be closed by #7
