### ISSUE TITLE
rename repo ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter-sphinx-theme#6]
Should we rename the repo to jupyter-sphinx-theme for consistency ?

**Comment by willingc** [comment]
@Carreau @jdfreder This seems like a reasonable request to me. It will likely minimize the number of random users that would mistake as the "Sphinx theme" and would send questions mistakenly here.

**Comment by jdfreder** [comment]
:+1:

**Comment by willingc** [comment]
Rock on @jdfreder

**Comment by Carreau** [comment]
Thanks !
